// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTKWHIZnoh4LWSdjYE79WaJQyrEV25GMk',
    appId: '1:115591952018:web:04e8f6511f76c6e045584b',
    messagingSenderId: '115591952018',
    projectId: 'assistantpro-1',
    authDomain: 'assistantpro-1.firebaseapp.com',
    databaseURL: 'https://assistantpro-1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'assistantpro-1.appspot.com',
    measurementId: 'G-R8RKZYDD3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1dRPqldlDXkxVfJz2pgACJYiFA4fXNlg',
    appId: '1:115591952018:android:5e195f7c720ebefb45584b',
    messagingSenderId: '115591952018',
    projectId: 'assistantpro-1',
    databaseURL: 'https://assistantpro-1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'assistantpro-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz594P_egE0J9sPgQyrPhZDJUalwIEHJ0',
    appId: '1:115591952018:ios:518476d9bd3a46cd45584b',
    messagingSenderId: '115591952018',
    projectId: 'assistantpro-1',
    databaseURL: 'https://assistantpro-1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'assistantpro-1.appspot.com',
    iosClientId: '115591952018-33hqh2kqtp1bbbc1qhgptfst5325er4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.assistantpro',
  );
}
